version: '3.8'

services:
  api:
    container_name: Boilerplate_api_service 
    build:
      context: .
      dockerfile: Dockerfile 
      target: development 
    env_file:
      - .env 
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules 
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    depends_on:
      db:
        condition: service_healthy
    command: npm run start:dev

  db:
    image: postgres:15-alpine 
    container_name: Boilerplate_db_service 
    env_file:
      - .env 
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "${DB_PORT:-5432}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USERNAME} -d ${DB_DATABASE}"]
      interval: 10s
      timeout: 5s   
      retries: 5    

volumes:
  postgres_data:
